version: "3.8"

services:
  web:
    depends_on:
      - api

    build: ./client
    ports:
      - 5173:5173

    environment:
      PUBLIC_API_URL: http://127.0.0.1:8090

    volumes:
      - ./client:/app

  api:
    build: ./backend
    ports:
      - 8090:8090

    volumes:
      - ./backend:/app
      # - ./backend/pb_data:/app/pb_data

