version: "3.8"

services:
  web:
    container_name: web
    restart: always
    depends_on:
      - api

    build: ./client
    ports:
      - 5173:5173

    env_file:
      - ./client/.env

    volumes:
      - ./client:/app

  api:
    container_name: api
    restart: unless-stopped
    build: ./backend
    ports:
      - 8090:8090

    volumes:
      - ./backend:/app
      - ./backend/pb_data:/app/pb_data

